trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: common
  - name: imageRepository
    value: sat/service1
  - name: imageTag
    value: $(Build.BuildId)
  - name: additionalTerraformVariables
    value: >
      -var="image_repository=$(imageRepository)"
      -var="image_tag=$(imageTag)"

resources:
  repositories:
    - repository: DevOps-Templates
      type: github
      endpoint: sliwa880
      name: sliwa880/pipeline_templates
      ref: main # użycie ostatniego commita na branchu "main"

    - repository: terraform-modules
      type: github
      endpoint: sliwa880
      name: sliwa880/terraform-modules
      ref: refs/tags/daprTag # użycie commita do którego jest przypisany tag "daprTag"
  
stages:
  - template: template-build-and-push-image.yml@DevOps-Templates
    parameters:
      repository: $(imageRepository)
      dockerFile: src/Dockerfile  
      buildContext: src
      containerRegistryName: $(containerRegistryName)
      containerRegistryServiceConnection: $(containerRegistryServiceConnection)
      imageTag: $(imageTag)


  - template: template-deploy-infra-to-env.yml@DevOps-Templates
    parameters:
      dependsOn: build
      serviceName: service1
      environment: test
      serviceConnectionAzure: $(serviceConnectionAzure)
      terraformBackendResourceGroup: $(terraformBackendResourceGroup)
      terraformBackendStorageAccount: $(terraformBackendStorageAccount)
      additionalTerraformCommandOptions: $(additionalTerraformVariables) 